### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by toddams** [Qmannn/SecureRemoteExplorer#2]
Здравствуй Максим, 

Можешь скинуть дамб базы данных или скрипт что бы воссоздать структуру таблиц, буду очень благодарен!

**Comment by Qmannn** [comment]
Иван, доброго времени суток,

Залил бекап базы в репозиторий _./SecureRemoteExplorer/DbBackup/ExplorerDataBase.backup_
Сервер бд - PostgreSql.

Не за что :)
