### ISSUE TITLE
Шифрование

### ISSUE THREAD

**Issue by OpasniyOchen** [Qmannn/SecureRemoteExplorer#3]
Здравствуй Максим!
Ключ,который пользователь вводит для обмена файлами - где он используется?
в каком шифровании?
Заранее благодарен

**Comment by Qmannn** [comment]
Здравствуй, Очень Опасный!

Ключ, введенный пользователем используется для шифрования сгенерированного закрытого асимметричного(RSA) ключа пользователя. С его помощью симметричным шифрованием AES256 шифруется закрытый ключ.

Обмен файлами организован таким образом, что при передаче файла пользователю он шифруется асимметричным шифрованием по случайно сгенерированному временному ключу, который после шифрования, в свою очередь, шифруется асимметричным шифрованием по открытому ключу пользователя получателя. Когда пользователь-получатель файла захочет его(файл) принять - он вводит ключ для обмена файлами, с помощью которого расшифровывается его закрытый асимметричный ключ, затем с помощью закрытого асимметричного ключа расшифровывается случайно сгенерированный при шифровании файла временный ключ симметричного шифрования, а затем файл расшифровывается и шифруется по новому ключу, выбранному пользователем.

Я надеюсь, что ответил на заданный вопрос. Если нужно - могу поискать пояснительную записку к проекту, там все описано. Это была курсовая работа.
